# -*- coding: utf-8 -*-
"""
Created on Mon Oct 19 16:02:49 2020

@author: Chai Wah Wu
"""

import numpy as np
import matplotlib.pyplot as plt
from sympy import nextprime
N = 2*10**5+1
p, x, y = 3, np.zeros(N,dtype=np.int), np.zeros(N,dtype=np.int)
for i in range(1,N):
    q = p % 10
    if q == 1: #E
        v = [1,0]
    elif q == 3: #N
        v = [0,1]
    elif q == 7: #W
        v = [-1,0]
    elif q == 9: #S
        v = [0,-1]
    x[i] = x[i-1]+v[0]
    y[i] = y[i-1]+v[1]
    p = nextprime(p)
    if p == 5:
        p = nextprime(p)
plt.plot(x,y,'c-',[0],[0],'ro')
plt.xlabel('x')
plt.ylabel('y')
plt.title('A 2D walk generated by primes')
    

